# -*- coding: utf-8 -*-
"""cleansing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVZeoFqnZii9fZlMPo6LFdlcev3TaQAj

Exercise #3 - Write your own module for cleansing data and save as ".py" file.

Cleansing Function
 - Rebuild Missing Data (check Null/NaN) -> 1 def
 - Standardise Data -> 1 def
 - Normalise Data
 - De-Duplicate
"""

def x_standard(x, x_mean, x_stdev):
  return (x-x_mean)/x_stdev

def x_norm(x, min, max):
  return (x-min)/(max-min)